apiVersion: v1
kind: PersistentVolume
metadata:
  name: activity-pv
  namespace: activity
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /home/admin/activity-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: DoesNotExist    

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: activity-pvc
  namespace: activity
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi