kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: activity-api
  name: activity-api
  namespace: activity
spec:
  type: NodePort
  ports:
    - port: 7061
      targetPort: api
      nodePort: 32235
      name: api
  selector:
    name: activity-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-api
  namespace: activity
spec:
  replicas: 2
  selector:
    matchLabels:
      name: activity-api
  template:
    metadata:
      labels:
        name: activity-api
    spec:
      hostNetwork: true
      hostname: activity-api
      subdomain: activity
      containers:
        - name: activity-api
          image: vmapi/hubcentral:activity.api.1.0.16
          ports:
            - name: api
              containerPort: 7061
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: "http://+:7061"
            - name: TZ
              value: "Asia/Bangkok"
            - name: Serilog__Sink
              value: file
            - name: Serilog__MinimumLevel__Override__Microsoft
              value: Information            
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          volumeMounts:
            - name: data-vol
              mountPath: /app/logs
              subPath: activity-api-logs
      volumes:
        - name: data-vol
          persistentVolumeClaim:
            claimName: activity-pvc
      imagePullSecrets:
        - name: registry-secret-clound
